version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - 'local.env'
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - 'local.env'
    ports:
      - 5432:5432

volumes:
  postgres_data:
